name: Simple_CI
on:
  workflow_dispatch:
  push:
   branches: [master]
  pull_request:
   branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run a cmd command"
        run: echo "hello world"
